name: sb-proxy

services:
  server:
    container_name: sb-proxy
    image: lucashmsilva/sponsor-block-proxy:latest
    ports:
      - 4480:80
    restart: always
    networks:
      - homelab

networks:
  homelab:
    external: true